### ISSUE TITLE
find a way to give timeslices

### ISSUE THREAD

**Issue by rbouqueau** [RodolpheFouquet/git-stats#2]
for example, rbouqueau between 2009/05/25 and 2009/05/24 (inclusive) is handled differently

it is important for copyright purposes when contributors work for different employers (or for themselves)

how could we do that?

**Comment by RodolpheFouquet** [comment]
Would you like to have, for example, 2 lines?

I could spend time to add a json config file to allow you to specify several timespans, and in the result you would have:

```
rbouqueau 2009-05-24 to 2009-05-25 | stats blablabla
rbouqueau (otherwise)              | stats blablabla
```

**Comment by rbouqueau** [comment]
would be great, thanks :)

**Comment by RodolpheFouquet** [comment]
```
{
  "periods": [
    { "user": "rbouqueau",
      "start": "2009-05-24",
      "end": "2009-05-25",
      "alias": "working at telecom"
    }
  ]
}
```

Would give:

```
rbouqueau (working at telecom)| stats blablabla
rbouqueau (otherwise)         | stats blablabla
```

Seems good for you?

And adding multiple periods could be

```
{
  "periods": [
    { "user": "rbouqueau",
      "start": "2009-05-24",
      "end": "2009-05-25",
      "alias": "working at telecom"
    },
   { "user": "rbouqueau",
      "start": "2009-05-26",
      "end": "2009-05-30",
      "alias": "working with unicorn superpowers, lasers and stuff"
    }
  ]
}
```

**Comment by rbouqueau** [comment]
Good. We need to allow end value in the future so that the same script can be used everytime e.g.

```
{
  "periods": [
    { "user": "rbouqueau",
      "start": "2000-01-01",
      "end": "2009-05-24",
      "alias": "working at telecom"
    },
   { "user": "rbouqueau",
      "start": "2009-05-26",
      "end": "2009-05-30",
      "alias": "working with unicorn superpowers, lasers and stuff"
    }
   { "user": "rbouqueau",
      "start": "2009-06-01",
      "end": "2079-05-30",
      "alias": "radio gaga"
    }
  ]
}
```

**Comment by RodolpheFouquet** [comment]
Why would you do that? Evey commit that wouldn't be in the specified timespan would be put in an "otherwise" section.

**Comment by RodolpheFouquet** [comment]
Though I might add support for timespans without start or end point.

Without start, it would be "everything before the end date", and without end point it would be "everything after the start date".

**Comment by rbouqueau** [comment]
> Though I might add support for timespans without start or end point.

That was my point. But I also imagined that people could specify something wrong anyway (i.e. overlaps).

Any of these is fine for me :)
